feat(settlement):sequence diagrams for continuous gross settlement
mojaloop/documentation pull request #304
Opened 2021-02-19 13:35 UTC by shashi165

### Summary
1. sequence diagram for CGS

2021-02-24 13:55 UTC, mdebarros requested changes
Hey @shashi165,

It's looking good, but I do have some comments for your consideration.

2021-02-24 13:55 UTC, mdebarros commented on mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence/seq-rules-handler.plantuml
> +                        RULES_HANDLER -> SETTLEMENT_DAO: Insert valid ledger entries
What happens if there is a failure on one of the DB calls?

2021-02-24 13:55 UTC, mdebarros commented on mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence/seq-rules-handler.plantuml
> +                                    update **`participantPosition`**
Do we not need any locks here before we update the participantPosition and participantPositionChange?

2021-03-01 20:38 UTC, shashi165 commented on mojaloop-technical-overview/central-settlements/settlement-process/README.md
> +[Sequence Diagram for Transfer Settlement Handler](transfer-settlement-handler-consume.md)
done..

2021-03-02 03:48 UTC, shashi165 commented on mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence/seq-rules-handler.plantuml
> +                SCRIPTS_LOADER --> RULES_HANDLER: script results
At the moment it's always LedgerEntries

2021-03-02 14:17 UTC, mdebarros commented on mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence/seq-rules-handler.plantuml
> +                SCRIPTS_LOADER --> RULES_HANDLER: script results
Yes, but depending on the rule, there may be "no results". I.e. what happens if there are no "outputs" (i.e. ledger entries) from the script

2021-03-02 14:17 UTC, mdebarros commented
> Hey @shashi165,
> 
> It's looking good, but I do have some comments for your consideration.

Hey @shashi165 @vgenev did you address all my questions?

2021-03-02 16:17 UTC, shashi165 commented on mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence/seq-rules-handler.plantuml
> +            RULES_HANDLER <-> RULES_HANDLER: check if ScriptMap[type][action][result] has valid script assigned
done

2021-03-02 17:13 UTC, shashi165 commented on mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence/seq-rules-handler.plantuml
> +                        RULES_HANDLER -> SETTLEMENT_DAO: Insert valid ledger entries
The whole transaction will rollback

2021-03-02 17:13 UTC, shashi165 commented on mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence/seq-rules-handler.plantuml
> +                SCRIPTS_LOADER --> RULES_HANDLER: script results
If there is no output from the script then we do nothing

2021-03-02 17:20 UTC, shashi165 commented on mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence/seq-rules-handler.plantuml
> +                                    update **`participantPosition`**
Need to discuss

2021-03-02 17:21 UTC, shashi165 commented on mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence/seq-gross-settlement-handler.plantuml
> +                end
The whole transaction will rollback

2021-03-05 09:46 UTC, mdebarros commented on mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence/seq-rules-handler.plantuml
> +                SCRIPTS_LOADER --> RULES_HANDLER: script results
@shashi165 should this not be reflected on the SDs?

2021-03-05 15:00 UTC, mdebarros approved these changes
+1

2021-03-10 10:15 UTC, elnyry-sam-k commented
@shashi165 , @vgenev - seeing this issue on CircleCI: https://app.circleci.com/pipelines/github/mojaloop/documentation/1427/workflows/9dedb110-eb64-48fa-9db8-e362bfa43f09/jobs/2694
```
1 plantuml files are out of sync. Please run npm run build:plantuml and try again.
```

Please review

2021-08-05 08:13 UTC, elnyry-sam-k commented
@shashi165 thinking of closing this one out.. do you still need it?

2021-08-06 13:55 UTC, elnyry-sam-k commented
@mdebarros @shashi165 @vgenev - closing this one out.. please reopen if necessary

2021-08-06 13:55 UTC, closed without merging