feat(settlements): feature#2234 add default settlements
mojaloop/documentation pull request #320
Opened 2021-07-13 09:54 UTC by vgenev

Changes:

* Added CGS and Rules functionality flows into settlements
* Added default settlement model

2021-07-13 13:23 UTC, elnyry-sam-k commented on mojaloop-technical-overview/central-settlements/settlement-process/README.md
> + Handle the updating of the POSITION and SETTLEMENT accounts for participants involved in a transfer where there is a settlement model defined as immeditate and gross on the POSITION account to facil
```suggestion
 Handle the updating of the POSITION and SETTLEMENT accounts for participants involved in a transfer where there is a settlement model defined as immediate and gross on the POSITION account to facilitate RTCGS (Real-Time Continuous Gross Settlement) per transfer.
```

2021-07-13 13:37 UTC, mdebarros requested changes
Additional changes that I cant include inline to the PR:
1. The [The Settlements Architecture](https://github.com/mojaloop/documentation/blob/master/mojaloop-technical-overview/central-settlements/assets/diagrams/architecture/Arch-Mojaloop-Settlements-PI4.svg) needs to updated to include the Gross and Rule handlers:   https://github.com/mojaloop/documentation/pull/320/files#diff-fbe4def7fe6a5932e90e70981c6808668f744f33f21d5a1fb8b4dc0b7a15e4b7R12

2021-07-13 13:37 UTC, mdebarros commented on mojaloop-technical-overview/central-settlements/settlement-process/rules-handler-consume.md
> +In order to support the various options for accumulating interchange or other fees, we need to generate
I am unsure as to why you are manually adding a "newline" through this document.?

Markdown will be rendered as HTML and will be wrapped appropriately according to the browser.

2021-07-13 13:37 UTC, mdebarros commented on mojaloop-technical-overview/central-settlements/settlement-process/rules-handler-consume.md
> +-   If the transaction is a wallet-to-wallet P2P transaction, then the receiver
I would include some additional information on how we "determine" a P2P transaction is a wallet-to-wallet. The reason for this being that it is not "standard" functionality from a Mojaloop perspective, and it requires an extension field in this example.

So I would include how this looks/works describing this fact and showing how the custom extension field was used for this purpose...and where it is introduced or sourced (i.e. is it the quote information, etc).

2021-07-13 13:37 UTC, mdebarros commented on mojaloop-technical-overview/central-settlements/settlement-process/rules-handler-consume.md
> +    2.  The rule evaluation itself uses a complex if statement.
```suggestion
    2.  The rule evaluation itself uses a combination of simple and/or complex nested if statements
```

2021-07-13 13:37 UTC, mdebarros commented on mojaloop-technical-overview/central-settlements/settlement-process/rules-handler-consume.md
> +
Please can you update the above example to be "typespafe", or at the minimum include a further note/example discussing this issue or perhaps linking to the issue itself.

2021-07-13 13:37 UTC, mdebarros commented on mojaloop-technical-overview/central-settlements/settlement-process/rules-handler-consume.md
> +The rule evaluation instatiates the calss and calls the appropriate functions.
`calss`?

2021-07-13 13:37 UTC, mdebarros commented on mojaloop-technical-overview/central-settlements/settlement-process/rules-handler-consume.md
> +myAction.addLedgerEntry(transaction.transactionId,
Code block?

2021-07-13 13:37 UTC, mdebarros commented on mojaloop-technical-overview/central-settlements/settlement-process/rules-handler-consume.md
> +Each rule file should be valid JS with the following header content:
It would be good to also explain how the rules engine works, and how it exposes an API and how that is linked to the header below, e.g. globals, functions, etc.

Let me know your thoughts on this.

2021-07-13 13:37 UTC, mdebarros commented on mojaloop-technical-overview/central-settlements/settlement-process/rules-handler-consume.md
> +| Header | Description | Required |
1. This table is floating with little context.
2. It needs a caption

Perhaps it should also be moved up to the description, and/or referenced from it (i.e. the missing caption).

2021-07-13 13:37 UTC, mdebarros commented on mojaloop-technical-overview/central-ledger/assets/database/central-ledger-schema-DBeaver.erd
>  <?xml version="1.0" encoding="UTF-8"?>
Please make sure this ERD and the generated PNG is up to date.

2021-07-13 13:37 UTC, mdebarros commented on mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence/seq-settlement-6.2.1.plantuml
> +                SETTLE_DAO -> SETTLE_DAO: filter out the SettlementWindowContent id List\n to exclude content that is not settlemed by default settlement model
Was this the only change here?

2021-07-14 08:20 UTC, vgenev commented on mojaloop-technical-overview/central-settlements/settlement-process/README.md
> + Handle the updating of the POSITION and SETTLEMENT accounts for participants involved in a transfer where there is a settlement model defined as immeditate and gross on the POSITION account to facil
I like immeditate :D

2021-07-21 11:56 UTC, vgenev commented on mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence/seq-settlement-6.2.1.plantuml
> +                SETTLE_DAO -> SETTLE_DAO: filter out the SettlementWindowContent id List\n to exclude content that is not settlemed by default settlement model
yes, in a way :D

2021-08-04 15:30 UTC, closed without merging