docs: move bulk transaction api sequence diagram to sdk-scheme-adapter repo
mojaloop/documentation pull request #387
Opened 2022-09-07 17:36 UTC by kirgene

2022-09-07 18:29 UTC, mdebarros commented on docs/technical/sdk-scheme-adapter/SDKBulk-API-Design.md
> +![Bulk Transfer Sequence Diagram Overview](https://raw.githubusercontent.com/mojaloop/sdk-scheme-adapter/mvp/bulk/docs/design-bulk-transfers/assets/api-sequence-diagram.svg)
https://raw.githubusercontent.com/mojaloop/sdk-scheme-adapter/mvp/bulk/docs/design-bulk-transfers/assets/api-sequence-diagram.svg --> 404 not found.

2022-09-07 20:03 UTC, kirgene commented on docs/technical/sdk-scheme-adapter/SDKBulk-API-Design.md
> +![Bulk Transfer Sequence Diagram Overview](https://raw.githubusercontent.com/mojaloop/sdk-scheme-adapter/mvp/bulk/docs/design-bulk-transfers/assets/api-sequence-diagram.svg)
this PR is dependent on the following one:
https://github.com/mojaloop/sdk-scheme-adapter/pull/363

2022-09-08 16:32 UTC, mdebarros requested changes

2022-09-08 16:32 UTC, mdebarros commented on docs/technical/sdk-scheme-adapter/SDKBulk-API-Design.md
> +![Bulk Transfer Sequence Diagram Overview](https://raw.githubusercontent.com/mojaloop/sdk-scheme-adapter/mvp/bulk/docs/design-bulk-transfers/assets/api-sequence-diagram.svg)
```suggestion
![Bulk Transfer Sequence Diagram Overview](https://raw.githubusercontent.com/mojaloop/sdk-scheme-adapter/mvp/bulk-sdk/docs/design-bulk-transfers/assets/api-sequence-diagram.svg)
```

2022-09-08 16:34 UTC, mdebarros approved these changes

2022-09-08 16:34 UTC, merged