feat(mojaloop/#3122): port deployment guide and update for v15 release
mojaloop/documentation pull request #409
Opened 2023-03-16 03:11 UTC by kleyow

2023-03-16 11:02 UTC, mdebarros requested changes
Minor tweaks

2023-03-30 07:30 UTC, elnyry-sam-k commented on docs/technical/deployment-guide/deployment-troubleshooting.md
> +1. Verify that that Mojaloop was deployed by checking that the helm chart(s) was installed by executing:
```suggestion
1. Verify that Mojaloop was deployed correctly (by checking that the helm chart(s) was installed) by executing:
```

2023-03-30 07:32 UTC, elnyry-sam-k commented on docs/technical/deployment-guide/deployment-troubleshooting.md
> +3. Note that the Mojaloop deployment via Helm can take a few minutes to initially startup depending on the system's available resources and specification. It is recommended that you wait at least 10m
is it 10 minutes

2023-03-30 07:35 UTC, elnyry-sam-k commented on docs/technical/deployment-guide/releases.md
> +| [15.0.0](https://github.com/mojaloop/helm/releases/tag/v15.0.0) | 2023/03/23 | &check; | Sprint release |
```suggestion
| [15.0.0](https://github.com/mojaloop/helm/releases/tag/v15.0.0) | 2023/03/23 | &check; | PI release |
```

2023-03-30 07:37 UTC, elnyry-sam-k commented on docs/technical/deployment-guide/upgrade-strategy-guide.md
> +1. all upgrades should be tested and verified in a pre-production environment
```suggestion
1. All upgrades should be tested and verified in a pre-production (Test or QA) environment initially
```

2023-03-30 07:37 UTC, elnyry-sam-k commented on docs/technical/deployment-guide/upgrade-strategy-guide.md
> +2. always consult the release notes as there may be some known issues, or useful notes that are applicable when upgrading
```suggestion
2. Always consult the release notes as there may be some known issues, or useful notes that are applicable when upgrading
```

2023-03-30 07:41 UTC, elnyry-sam-k commented on docs/technical/deployment-guide/upgrade-strategy-guide.md
> +2. Mojaloop installed with backend dependencies, with backend dependencies tightly coupled to the Helm installation
```suggestion
2. Mojaloop installed with backend dependencies, with backend dependencies tightly coupled to the Helm installation (This process will be deprecated from Mojaloop v15.0.0 onwards (including v15) though example backend deployment support is provided for testing, QA)
```

2023-03-30 09:10 UTC, mdebarros commented on docs/technical/deployment-guide/deployment-troubleshooting.md
> +3. Note that the Mojaloop deployment via Helm can take a few minutes to initially startup depending on the system's available resources and specification. It is recommended that you wait at least 10m
Its probably less now since the backends are deployed seperately.

It probably takes around 5m now, but milage will vary depending on your system. I.e. slow system means you will need to wait longer.

On my machine it takes around 8-12m, and on moja2 for example, it normally takes around 2-4m.

2023-03-30 09:12 UTC, mdebarros commented on docs/technical/deployment-guide/upgrade-strategy-guide.md
> +This document provides instructions on how to upgrade existing Mojaloop installations. It assumes that Mojaloop is currently installed using Helm, but these strategies can be applied in general.
No, "currently" is intended. 

Perhaps it should be replaced with "an existing Mojaloop deployment".

2023-03-30 09:18 UTC, mdebarros commented on docs/technical/deployment-guide/upgrade-strategy-guide.md
> +This document provides instructions on how to upgrade existing Mojaloop installations. It assumes that Mojaloop is currently installed using Helm, but these strategies can be applied in general.
```suggestion
This document provides instructions on how to upgrade existing Mojaloop installations. It assumes that Mojaloop is already installed using Helm, but these strategies can be applied in general.
```

2023-03-30 09:18 UTC, mdebarros commented on docs/technical/deployment-guide/upgrade-strategy-guide.md
> +This document provides instructions on how to upgrade existing Mojaloop installations. It assumes that Mojaloop is currently installed using Helm, but these strategies can be applied in general.
"currently" is intended.

2023-03-30 11:00 UTC, elnyry-sam-k commented on docs/technical/deployment-guide/deployment-troubleshooting.md
> +3. Note that the Mojaloop deployment via Helm can take a few minutes to initially startup depending on the system's available resources and specification. It is recommended that you wait at least 10m
ok thanks..

2023-03-30 11:01 UTC, mdebarros commented on docs/technical/deployment-guide/deployment-troubleshooting.md
> +3. Note that the Mojaloop deployment via Helm can take a few minutes to initially startup depending on the system's available resources and specification. It is recommended that you wait at least 10m
```suggestion
3. Note that the Mojaloop deployment via Helm can take a few minutes to initially startup depending on the system's available resources and specification. Expect this to take anything between 2-10 minutes.
```

2023-03-30 14:09 UTC, merged